### ISSUE TITLE
使用方面的咨询

### ISSUE THREAD

**Issue by 912988434** [kingzcheung/drone-aliyun-oss#2]
你好，我也是drone得用户，目前使用的是minio存储drone构建时候的缓存（比如maven依赖和docker基础镜像），最近考虑将缓存存储到阿里oss上，看到这个项目，有两个问题想咨询一下：
1. localfile为支持多个文件或者目录吗，比如java项目想将.m2和docker 目录给上传带oss上？上传时候会对localfile中的目录进行归档压缩吗？
2. 支持resote,rebuild模式吗，构建时候利用缓存的很多场景是先下载缓存，然后上传缓存。

（见谅见谅，英语不好，就用中文问了）

**Comment by kingzcheung** [comment]
抱歉，localfile 暂时没有做多个文件或者目录的上传，也不会自动归档压缩。不过其实drone是比较自由的，归档压缩你可以在上传前通过shell命令来做。

你描述的这个场景我不太理解，一般如果是构建docker镜像的话，不应该是存储docker镜像吗？

**Comment by dream-luckcy** [comment]
> 抱歉，localfile暂时没有做一些文件或者目录的上传，也不会自动归档压缩。不过实际上无人机是比较自由的，归档压缩你可以在上传前通过shell命令来做。
> 
> 你描述的这个场景我不太了解，一般如果是构建docker镜像的话，不应该是存储docker镜像吗？

是这样的，有点抱歉，之前描述的有点问题，场景是这样的
1、比如java项目构建，通常需要将maven/gradle的依赖的jar包缓存，构建前需要先将上次缓存的依赖包下载下来用来加速构建然后maven package 之后再将更新的依赖包上传，同理前端的项目构建时候的场景也是这样，先下载上次缓存的node_modules目录，然后npm run build之后需要将更新的node_modules给上传
2、 构建docker 镜像，虽然最终产物是镜像上传到镜像仓库，但是我们很多时候会可能会缓存构建时候的cache 用来加速构建，这样同样也是需要先下载缓存，然后再更新缓存。

**Comment by dream-luckcy** [comment]
是这样的，有点抱歉，之前描述的不太详细，场景是这样的
1、比如java项目构建，通常需要将maven/gradle的依赖的jar包缓存，构建前需要先将上次缓存的依赖包下载下来用来加速构建然后maven package 之后再将更新的依赖包作为缓存上传，同理前端的项目构建时候的场景也是这样，先下载上次缓存的node_modules目录，然后npm run build之后需要将更新的node_modules给上传
2、 构建docker 镜像，最终产物是镜像上传到harbor仓库，但是我们很多时候会可能会缓存构建时候的cache 用来加速构建，这样同样也是需要先下载缓存，然后再更新缓存。

**Comment by 912988434** [comment]
是这样的，有点抱歉，之前描述的不太详细，场景是这样的
1、比如java项目构建，通常需要将maven/gradle的依赖的jar包缓存，构建前需要先将上次缓存的依赖包下载下来用来加速构建然后maven package 之后再将更新的依赖包作为缓存上传，同理前端的项目构建时候的场景也是这样，先下载上次缓存的node_modules目录，然后npm run build之后需要将更新的node_modules给上传
2、 构建docker 镜像，最终产物是镜像上传到harbor仓库，但是我们很多时候会可能会缓存构建时候的cache 用来加速构建，这样同样也是需要先下载缓存，然后再更新缓存。

**Comment by kingzcheung** [comment]
一般同一个项目的依赖包都比较稳定，你可以通过为项目制作构建使用的自定义镜像，把.m2相关依赖打入自定义镜像来做加速。这样应该会比单纯的把jar包缓存到oss快一些，毕竟.m2 目录的文件也比较碎并且多。

drone 系统在多次构建中会自动使用镜像缓存的。
